apiVersion: 1

deleteDatasources:
  - name: MYINFLUX
    orgId: 1

datasources:
- name: ClickHouse
  type: grafana-clickhouse-datasource
  jsonData:
    defaultDatabase: default
    port: 9000
    host: clickhouse
    tlsSkipVerify: false
  secureJsonData:
    password:
